services:
  client:
    image: demo-postgres
    platform: wasi/wasm
    build:
      context: .
    environment:
      DATABASE_URL: postgres://wasmedge:rocks@db/testdb
      RUST_BACKTRACE: full
    restart: on-failure
    runtime: io.containerd.wasmedge.v1
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=wasmedge
      - POSTGRES_PASSWORD=rocks
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
